services:
    - docker
before_script:
    - sudo service postgresql stop
script:
    - cp app/.env.example app/.env
    - docker-compose build
    - docker-compose up -d postgres
    - docker-compose run composer install --ignore-platform-reqs
    - docker-compose up -d php-server
    - docker exec -it auth-php-server bash -c 'vendor/bin/phinx migrate'
    - docker exec -it auth-php-server bash -c 'vendor/bin/phpstan analyse'
    - docker exec -it auth-php-server bash -c 'vendor/bin/phpcs'
    - docker exec -it auth-php-server bash -c 'vendor/bin/codecept build'
    - docker exec -it auth-php-server bash -c 'vendor/bin/codecept run'
    - docker-compose down
