version: '3'

services:
  php-server:
    container_name: auth-php-server
    build:
      context: ./docker
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
  composer:
    image: composer
    container_name: composer
    command: install
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
  postgres:
    image: postgres:11.2
    container_name: postgresdatabase
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth-app
      POSTGRES_DB: auth
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
