version: '3'

services:
  php-server:
    container_name: auth-php-server
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "80:80"
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://postgres/auth -user=auth -password=auth-app -connectRetries=60 migrate
    volumes:
      - ./docker/flyway/:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2
    container_name: postgresdatabase
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth-app
      POSTGRES_DB: auth
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /mnt/swagger.json
    volumes:
      - ./docs:/mnt
    ports:
      - 8001:8080
volumes:
  db-data:
