version: '3'

services:
  php-server:
    container_name: auth-php-server
    build:
      context: ./docker
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
  composer:
    image: composer
    container_name: composer
    command: install
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
