version: '3'

services:
  php-server:
    container_name: auth-php-server
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
  composer:
    image: composer
    container_name: composer
    command: install --ignore-platform-reqs
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
  postgres:
    image: postgres:11.2
    container_name: postgresdatabase
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth-app
      POSTGRES_DB: auth
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /mnt/swagger.json
    volumes:
      - ./docs:/mnt
    ports:
      - 8001:8080
volumes:
  db-data:
