FROM php:7.4-apache
RUN apt-get update \
&& apt-get install -y libpq-dev curl zlib1g-dev libzip-dev \
&& docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
&& docker-php-ext-install pdo pdo_pgsql zip \
&& a2enmod rewrite
COPY ./app /var/www/html
COPY ./docker/apache/conf/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./docker/apache/conf/ports.conf /etc/apache2/ports.conf
CMD docker-php-entrypoint apache2-foreground
WORKDIR /var/www/html
RUN curl -sS https://getcomposer.org/installer | \
            php -- --install-dir=/usr/bin/ --filename=composer

RUN /usr/bin/composer install --no-dev
